/// The image node.
library;

import 'package:lexical_core/lexical_core.dart';

/// An image in the document.
///
/// A **decorator**: the model holds where the image is and how big it should
/// be, and the host draws it. That split is what keeps the node free of
/// Flutter and lets the same document render in a web client that has never
/// heard of `Image.network`.
///
/// A GIF is an image. Lexical has no separate node for one and neither does
/// this — the playground's "GIF" menu entry dispatches its ordinary insert
/// command with a `.gif` source, and Flutter animates it without being asked.
///
/// ## Wire format
///
/// ```json
/// { "type": "image", "version": 1,
///   "src": "https://…/flowers.jpg", "altText": "Ringelblumen",
///   "width": 480, "height": 320, "maxWidth": 500,
///   "showCaption": true,
///   "caption": { "editorState": { "root": { … } } } }
/// ```
///
/// This matches the Lexical **playground's** `ImageNode` field for field,
/// including two conventions that are easy to get wrong:
///
/// * `width` and `height` are `0` for "as large as it comes" — not `null`,
///   not absent. Upstream stores `'inherit'` internally and writes `0`.
/// * `maxWidth` is part of the document. It is arguably a presentation
///   policy, but it travels in the file, so dropping it would lose data on a
///   round trip. `ImageSizeLimits` can still narrow it per application.
///
/// `image` is not part of any published `@lexical/*` package — it lives in the
/// playground — so this shape is transcribed from that source rather than
/// generated by `gen_fixtures.mjs` like the core types. It cannot be verified
/// against a running Lexical automatically, which is exactly why the fixture
/// in this package's tests is written out in full.
///
/// ## The caption
///
/// Upstream's caption is a **nested editor**: a second editor instance per
/// image, with its own history and selection, serialized as
/// `{"editorState": …}`. This port has no nested editors, so the caption is
/// kept **verbatim** as the map it arrived as and exposed as plain text.
///
/// The consequence is worth stating plainly: a caption written on the web
/// keeps its formatting through any number of round trips here, and *editing*
/// one in Flutter replaces it with plain text. Losing the bold in a caption
/// someone deliberately edited is a fair trade; losing it by merely opening
/// the document would not be.
class ImageNode extends DecoratorNode {
  /// Creates an image showing [src].
  ImageNode({
    String src = '',
    String altText = '',
    double width = 0,
    double height = 0,
    double maxWidth = defaultMaxWidth,
    bool showCaption = false,
    Map<String, Object?>? caption,
  }) : _src = src,
       _altText = altText,
       _width = width,
       _height = height,
       _maxWidth = maxWidth,
       _showCaption = showCaption,
       _caption = caption;

  /// What the playground uses when nothing else is given.
  static const double defaultMaxWidth = 500;

  String _src;
  String _altText;
  double _width;
  double _height;
  double _maxWidth;
  bool _showCaption;
  Map<String, Object?>? _caption;

  @override
  String get type => 'image';

  /// An image is its own block; it is not part of a line of text.
  @override
  bool get isInline => false;

  @override
  ImageNode clone() => ImageNode(
    src: _src,
    altText: _altText,
    width: _width,
    height: _height,
    maxWidth: _maxWidth,
    showCaption: _showCaption,
    caption: _caption,
  );

  @override
  void afterCloneFrom(covariant ImageNode prev) {
    super.afterCloneFrom(prev);
    _src = prev._src;
    _altText = prev._altText;
    _width = prev._width;
    _height = prev._height;
    _maxWidth = prev._maxWidth;
    _showCaption = prev._showCaption;
    _caption = prev._caption;
  }

  /// Where the image comes from: a URL, a data URI, an asset path.
  ///
  /// Stored verbatim, like every other address in these packages, so
  /// documents round-trip unchanged. Decide what is loadable at the point of
  /// loading — see `defaultImageResolver`.
  String get src => getLatest<ImageNode>()._src;

  /// The alternative text. Empty means decorative.
  String get altText => getLatest<ImageNode>()._altText;

  /// The chosen width, or `0` for the image's own.
  double get width => getLatest<ImageNode>()._width;

  /// The chosen height, or `0` for the image's own.
  double get height => getLatest<ImageNode>()._height;

  /// The largest width this image should take, from the document.
  double get maxWidth => getLatest<ImageNode>()._maxWidth;

  /// Whether a caption is shown.
  bool get showCaption => getLatest<ImageNode>()._showCaption;

  /// The caption's nested editor state, verbatim, or `null`.
  ///
  /// Preserved rather than interpreted: this port cannot edit a nested
  /// editor, and rewriting what it cannot read would destroy it.
  Map<String, Object?>? get caption => getLatest<ImageNode>()._caption;

  /// The caption as plain text — what this port can show and edit.
  String get captionText {
    final state = caption;
    if (state == null) return '';
    final root = state['root'];
    if (root is! Map<String, Object?>) return '';
    return _plainText(root).trim();
  }

  /// Points the image at [value].
  ImageNode setSrc(String value) => getWritable<ImageNode>().._src = value;

  /// Sets the alternative text.
  ImageNode setAltText(String value) =>
      getWritable<ImageNode>().._altText = value;

  /// Resizes the image. Zero means "as large as it comes".
  ImageNode setSize(double width, double height) {
    final writable = getWritable<ImageNode>();
    writable._width = width.isFinite && width > 0 ? width : 0;
    writable._height = height.isFinite && height > 0 ? height : 0;
    return writable;
  }

  /// Sets the largest width the document asks for.
  ImageNode setMaxWidth(double value) =>
      getWritable<ImageNode>().._maxWidth = value;

  /// Shows or hides the caption.
  ImageNode setShowCaption({required bool value}) =>
      getWritable<ImageNode>().._showCaption = value;

  /// Replaces the caption with plain [text], or removes it with `null`.
  ///
  /// This **discards** any formatting a nested caption carried, which is why
  /// it only ever runs when someone edits the caption on purpose.
  ImageNode setCaptionText(String? text) {
    final writable = getWritable<ImageNode>();
    if (text == null) {
      writable._caption = null;
      writable._showCaption = false;
      return writable;
    }
    writable._caption = _captionStateFor(text);
    writable._showCaption = true;
    return writable;
  }

  /// Replaces the caption with a nested editor state verbatim.
  ImageNode setCaption(Map<String, Object?>? state) =>
      getWritable<ImageNode>().._caption = state;

  /// A stand-in for copy and for the accessibility tree.
  @override
  String getTextContent() {
    final parts = [
      if (_altText.isNotEmpty) _altText,
      if (showCaption && captionText.isNotEmpty) captionText,
    ];
    return parts.join(' — ');
  }

  @override
  Map<String, Object?> exportJson() => {
    ...super.exportJson(),
    'altText': _altText,
    'caption': {'editorState': _caption ?? _emptyCaptionState()},
    'height': _asWire(_height),
    'maxWidth': _asWire(_maxWidth),
    'showCaption': _showCaption,
    'src': _src,
    'width': _asWire(_width),
  };

  @override
  void updateFromJson(Map<String, Object?> json) {
    super.updateFromJson(json);
    final src = json['src'];
    _src = src is String ? src : '';
    final altText = json['altText'];
    _altText = altText is String ? altText : '';
    _width = _dimension(json['width']);
    _height = _dimension(json['height']);
    final maxWidth = json['maxWidth'];
    _maxWidth = maxWidth is num && maxWidth > 0
        ? maxWidth.toDouble()
        : defaultMaxWidth;
    _showCaption = json['showCaption'] == true;
    final caption = json['caption'];
    if (caption is Map<String, Object?>) {
      final state = caption['editorState'];
      _caption = state is Map<String, Object?> ? state : null;
    } else {
      _caption = null;
    }
  }

  /// A dimension from JSON. Anything unusable becomes `0` — "its own size".
  ///
  /// A document from another writer is untrusted input, and an image of width
  /// `-1` or `NaN` should not be able to break a layout.
  static double _dimension(Object? value) {
    final number = value is num ? value.toDouble() : 0.0;
    if (!number.isFinite || number <= 0) return 0;
    return number;
  }

  /// Integers stay integers on the wire: upstream writes `0`, not `0.0`, and
  /// a fixed-point comparison notices the difference.
  static Object _asWire(double value) =>
      value == value.roundToDouble() ? value.round() : value;

  static String _plainText(Map<String, Object?> node) {
    final text = node['text'];
    if (text is String) return text;
    final children = node['children'];
    if (children is! List) return '';
    final buffer = StringBuffer();
    for (final child in children) {
      if (child is Map<String, Object?>) buffer.write(_plainText(child));
    }
    // A block boundary is a space once it is flattened to a line.
    return node['type'] == 'root' ? buffer.toString() : '$buffer ';
  }

  /// An empty nested editor state, in the shape core itself produces.
  static Map<String, Object?> _emptyCaptionState() => _captionStateFor('');

  /// A nested editor state holding [text], built by the real serializer.
  ///
  /// Hand-writing this map would mean maintaining a second copy of the wire
  /// format, and the first field the core adds is the one that would be
  /// missing here.
  static Map<String, Object?> _captionStateFor(String text) {
    final editor = LexicalEditor();
    editor.update(() {
      final paragraph = $createParagraphNode();
      if (text.isNotEmpty) paragraph.append($createTextNode(text));
      $getRoot()
        ..clear()
        ..append(paragraph);
    }, discrete: true);
    return editor.editorState.toJson();
  }

  @override
  String toString() => 'ImageNode($_src, ${_width}x$_height)';
}

/// Creates an image, applying any registered node replacement.
ImageNode $createImageNode({
  required String src,
  String altText = '',
  double width = 0,
  double height = 0,
  double maxWidth = ImageNode.defaultMaxWidth,
  bool showCaption = false,
  Map<String, Object?>? caption,
}) => $applyNodeReplacement(
  ImageNode(
    src: src,
    altText: altText,
    width: width,
    height: height,
    maxWidth: maxWidth,
    showCaption: showCaption,
    caption: caption,
  ),
);
