import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lexical_core/lexical_core.dart';
import 'package:lexical_embed/lexical_embed.dart';
import 'package:lexical_markdown/lexical_markdown.dart';

LexicalEditor _editor() => LexicalEditor(nodes: embedNodes);

/// A document with one of each embed, in the playground's own shape.
///
/// None of the three lives in a published `@lexical/*` package, so this is
/// transcribed from `lexical-playground/src/nodes/` rather than generated by
/// `gen_fixtures.mjs`. Writing it out in full is what makes drift visible.
const Map<String, Object?> _playgroundEmbeds = <String, Object?>{
  'root': <String, Object?>{
    'children': <Object?>[
      <String, Object?>{
        'format': '',
        'type': 'youtube',
        'version': 1,
        'videoID': 'dQw4w9WgXcQ',
      },
      <String, Object?>{
        'format': 'center',
        'type': 'tweet',
        'version': 1,
        'id': '1234567890123456789',
      },
      <String, Object?>{
        'format': '',
        'type': 'figma',
        'version': 1,
        'documentID': 'PsvOWUD6t4NB4B9ZLKMKmy',
      },
    ],
    'direction': null,
    'format': '',
    'indent': 0,
    'type': 'root',
    'version': 1,
  },
};

MarkdownTransformers get _transformers =>
    defaultMarkdownTransformers.extend(elements: embedTransformers);

void main() {
  group('the wire format', () {
    test('the playground shape round-trips as a fixed point', () {
      final editor = _editor();
      editor.setEditorState(editor.parseEditorState(_playgroundEmbeds));
      expect(editor.editorState.toJson(), _playgroundEmbeds);
    });

    test('the fields arrive where they belong', () {
      final editor = _editor();
      editor.setEditorState(editor.parseEditorState(_playgroundEmbeds));
      editor.read(() {
        final children = $getRoot().children.toList();
        final video = children[0] as YouTubeNode;
        expect(video.videoId, 'dQw4w9WgXcQ');
        expect(video.watchUrl, 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
        expect(
          video.embedUrl,
          'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
        );

        final tweet = children[1] as TweetNode;
        expect(tweet.tweetId, '1234567890123456789');
        // The alignment DecoratorBlockNode carries, and the reason it exists.
        expect(tweet.format, ElementFormat.center);

        final figma = children[2] as FigmaNode;
        expect(figma.documentId, 'PsvOWUD6t4NB4B9ZLKMKmy');
      });
    });

    test('the text stand-in is the URL upstream uses', () {
      final editor = _editor();
      editor.setEditorState(editor.parseEditorState(_playgroundEmbeds));
      editor.read(() {
        final children = $getRoot().children.toList();
        expect(
          children[0].getTextContent(),
          'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        );
        expect(
          children[1].getTextContent(),
          'https://x.com/i/web/status/1234567890123456789',
        );
        expect(
          children[2].getTextContent(),
          'https://www.figma.com/file/PsvOWUD6t4NB4B9ZLKMKmy',
        );
      });
    });

    test('a missing id decodes to an empty one, not to a crash', () {
      final editor = _editor();
      editor.setEditorState(
        editor.parseEditorState(<String, Object?>{
          'root': <String, Object?>{
            'children': <Object?>[
              <String, Object?>{'type': 'youtube', 'version': 1},
            ],
            'direction': null,
            'format': '',
            'indent': 0,
            'type': 'root',
            'version': 1,
          },
        }),
      );
      editor.read(() {
        expect(($getRoot().getFirstChild()! as YouTubeNode).videoId, isEmpty);
      });
    });
  });

  group('recognising a URL', () {
    test('every YouTube spelling gives the same id', () {
      for (final url in [
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'https://youtu.be/dQw4w9WgXcQ',
        'https://www.youtube.com/embed/dQw4w9WgXcQ',
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=42s',
        'https://m.youtube.com/watch?v=dQw4w9WgXcQ',
      ]) {
        final target = matchEmbedUrl(url);
        expect(target?.kind, EmbedKind.youtube, reason: url);
        expect(target?.id, 'dQw4w9WgXcQ', reason: url);
      }
    });

    test('an id of the wrong length is not a video', () {
      // The pattern alone matches far too much; upstream checks the length
      // and so does this.
      expect(matchEmbedUrl('https://www.youtube.com/watch?v=short'), isNull);
    });

    test('both names of the same site work', () {
      for (final url in [
        'https://twitter.com/lexicaljs/status/1234567890123456789',
        'https://x.com/lexicaljs/status/1234567890123456789',
      ]) {
        final target = matchEmbedUrl(url);
        expect(target?.kind, EmbedKind.tweet, reason: url);
        expect(target?.id, '1234567890123456789', reason: url);
      }
    });

    test('a Figma file and a prototype are both recognised', () {
      for (final url in [
        'https://www.figma.com/file/PsvOWUD6t4NB4B9ZLKMKmy/Design',
        'https://figma.com/proto/PsvOWUD6t4NB4B9ZLKMKmy',
      ]) {
        final target = matchEmbedUrl(url);
        expect(target?.kind, EmbedKind.figma, reason: url);
        expect(target?.id, 'PsvOWUD6t4NB4B9ZLKMKmy', reason: url);
      }
    });

    test('a look-alike host is not Figma', () {
      // Upstream's pattern leaves the dot unescaped, so it accepts this.
      expect(
        matchEmbedUrl('https://figmaXcom/file/PsvOWUD6t4NB4B9ZLKMKmy'),
        isNull,
      );
    });

    test('every other video source is not an embed', () {
      // Not an oversight to fix later: Lexical has no node that could hold
      // these, so pretending otherwise would produce unopenable documents.
      for (final url in [
        'https://vimeo.com/76979871',
        'https://example.org/clip.mp4',
        'https://example.org/stream.m3u8',
        'https://www.dailymotion.com/video/x8abcde',
        '',
        'not a url',
      ]) {
        expect(matchEmbedUrl(url), isNull, reason: url);
      }
    });
  });

  group('inserting', () {
    test('a pasted video takes the empty line it was pasted on', () {
      final editor = _editor();
      registerRichText(editor);
      registerEmbed(editor);
      editor.update(() {
        $getRoot()
          ..clear()
          ..append($createParagraphNode()..append($createTextNode('davor')))
          ..append($createParagraphNode());
        ($getRoot().getLastChild()! as ElementNode).selectEnd();
      }, discrete: true);

      final handled = editor.dispatchCommand(
        insertEmbedFromUrlCommand,
        'https://youtu.be/dQw4w9WgXcQ',
      );

      expect(handled, isTrue);
      editor.read(() {
        expect($getRoot().children.map((node) => node.type), [
          'paragraph',
          'youtube',
          'paragraph',
        ]);
        assertTreeIntegrity($getRoot());
      });
    });

    test(
      'an embed is never the last block, so the caret has somewhere to go',
      () {
        final editor = _editor();
        registerEmbed(editor);
        editor.update(() => $getRoot().clear(), discrete: true);
        editor.dispatchCommand(insertYouTubeCommand, 'dQw4w9WgXcQ');
        editor.read(() {
          expect($getRoot().getLastChild(), isA<ParagraphNode>());
        });
      },
    );

    test('an unsupported URL is declined, not swallowed', () {
      // Returning false is what lets an auto-link handler have it instead.
      final editor = _editor();
      registerEmbed(editor);
      editor.update(() => $getRoot().clear(), discrete: true);

      final handled = editor.dispatchCommand(
        insertEmbedFromUrlCommand,
        'https://vimeo.com/76979871',
      );

      expect(handled, isFalse);
      editor.read(() {
        expect($getRoot().children.whereType<YouTubeNode>(), isEmpty);
      });
    });
  });

  group('markdown', () {
    test('a tweet uses upstream\'s own spelling', () {
      final editor = _editor();
      editor.update(
        () => $convertFromMarkdown(
          '<tweet id="1234567890123456789" />',
          transformers: _transformers,
        ),
        discrete: true,
      );
      editor.read(() {
        expect($getRoot().getFirstChild(), isA<TweetNode>());
      });
      expect(
        editor.read(() => $convertToMarkdown(transformers: _transformers)),
        '<tweet id="1234567890123456789" />',
      );
    });

    test('a video is a URL on its own line, and comes back as a video', () {
      final editor = _editor();
      editor.update(
        () => $convertFromMarkdown(
          'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          transformers: _transformers,
        ),
        discrete: true,
      );
      editor.read(() {
        expect(
          ($getRoot().getFirstChild()! as YouTubeNode).videoId,
          'dQw4w9WgXcQ',
        );
      });
      expect(
        editor.read(() => $convertToMarkdown(transformers: _transformers)),
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      );
    });

    test('a URL inside a sentence stays text', () {
      final editor = _editor();
      const line = 'Sieh dir https://youtu.be/dQw4w9WgXcQ an';
      editor.update(
        () => $convertFromMarkdown(line, transformers: _transformers),
        discrete: true,
      );
      editor.read(() {
        expect($getRoot().getFirstChild(), isA<ParagraphNode>());
      });
      expect(
        editor.read(() => $convertToMarkdown(transformers: _transformers)),
        line,
      );
    });

    test('lines the rule must not claim survive it', () {
      // The first rule to match a line is the one that gets it, so a rule
      // this broad would quietly take these away from the others.
      for (final line in ['Hallo', '> Zitat', '- Punkt', '# Titel']) {
        final editor = _editor();
        editor.update(
          () => $convertFromMarkdown(line, transformers: _transformers),
          discrete: true,
        );
        expect(
          editor.read(() => $convertToMarkdown(transformers: _transformers)),
          line,
          reason: line,
        );
      }
    });

    test('a URL that is not embeddable stays a line of text', () {
      final editor = _editor();
      const line = 'https://vimeo.com/76979871';
      editor.update(
        () => $convertFromMarkdown(line, transformers: _transformers),
        discrete: true,
      );
      editor.read(() {
        expect($getRoot().getFirstChild(), isA<ParagraphNode>());
      });
      expect(
        editor.read(() => $convertToMarkdown(transformers: _transformers)),
        line,
      );
    });

    test('without the rules an embed exports as nothing, not as a crash', () {
      final editor = _editor();
      editor.setEditorState(editor.parseEditorState(_playgroundEmbeds));
      expect(
        editor.read(
          () => $convertToMarkdown(transformers: defaultMarkdownTransformers),
        ),
        isEmpty,
      );
    });
  });

  group('the card', () {
    testWidgets('it shows the title and opens on tap', (tester) async {
      final opened = <String>[];
      await tester.pumpWidget(
        Directionality(
          textDirection: TextDirection.ltr,
          child: LexicalEmbedView(
            kind: EmbedKind.youtube,
            id: 'dQw4w9WgXcQ',
            url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            label: 'Ein Video',
            onOpen: (kind, url) => opened.add(url),
            // The default resolver would try to fetch a thumbnail.
            thumbnailResolver: (kind, id) => null,
          ),
        ),
      );

      expect(find.text('Ein Video'), findsOneWidget);
      await tester.tap(find.byType(LexicalEmbedView));
      expect(opened, ['https://www.youtube.com/watch?v=dQw4w9WgXcQ']);
    });

    test('only YouTube has a thumbnail that can be fetched', () {
      expect(
        defaultEmbedThumbnailResolver(EmbedKind.youtube, 'dQw4w9WgXcQ'),
        isNotNull,
      );
      expect(defaultEmbedThumbnailResolver(EmbedKind.tweet, '1'), isNull);
      expect(defaultEmbedThumbnailResolver(EmbedKind.figma, 'a'), isNull);
    });
  });
}
